services:
  - type: web
    name: your-django-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-django-db
          property: connectionString